export const SYNONYMS = {
  couch: 'sofa',
  couhc: 'sofa',
  coutch: 'sofa',
  settee: 'sofa',
  sectional: 'sofa',
  chair: 'chair',
  chaur: 'chair',
  chiar: 'chair',
  char: 'chair',
  cahir: 'chair',
  table: 'table',
  tabel: 'table',
  tabl: 'table',
  teble: 'table',
  tbale: 'table',
  bed: 'bed',
  bet: 'bed',
  bead: 'bed',
  bedd: 'bed',
  cabinet: 'cabinet',
  cabnit: 'cabinet',
  cabnet: 'cabinet',
  wardrobe: 'wardrobe',
  wadrobe: 'wardrobe',
  wardobe: 'wardrobe',
  almari: 'almirah',
  almaari: 'almirah',
  almira: 'almirah',

  black: 'black',
  blk: 'black',
  balck: 'black',
  blakc: 'black',
  white: 'white',
  wht: 'white',
  whit: 'white',
  wihte: 'white',
  brown: 'brown',
  borwn: 'brown',
  brow: 'brown',
  gray: 'gray',
  grey: 'gray',
  gry: 'gray',
  graey: 'gray',
  blue: 'blue',
  blu: 'blue',
  bleu: 'blue',
  red: 'red',
  reed: 'red',
  rad: 'red',

  leather: 'leather',
  lether: 'leather',
  leater: 'leather',
  leathe: 'leather',
  wood: 'wood',
  wod: 'wood',
  woood: 'wood',
  wooden: 'wood',
  metal: 'metal',
  matel: 'metal',
  metla: 'metal',
  fabric: 'fabric',
  fabrik: 'fabric',
  fabic: 'fabric',
  cotton: 'cotton',
  coton: 'cotton',
  cottn: 'cotton',

  small: 'small',
  smal: 'small',
  smll: 'small',
  samll: 'small',
  large: 'large',
  larg: 'large',
  laerg: 'large',
  big: 'large',
  medium: 'medium',
  medim: 'medium',
  midium: 'medium',
  med: 'medium',

  king: 'king',
  knig: 'king',
  kiing: 'king',
  queen: 'queen',
  quean: 'queen',
  quen: 'queen',
  single: 'single',
  singel: 'single',
  singl: 'single',
  double: 'double',
  dobule: 'double',
  dubble: 'double',
};

export const STOP_WORDS = new Set([
  'set',
  'with',
  'and',
  'or',
  'the',
  'a',
  'an',
  'in',
  'on',
  'at',
  'for',
  'by',
  'of',
  'to',
  'from',
  'up',
  'out',
  'if',
  'about',
  'into',
  'over',
  'after',
  'best',
  'good',
  'nice',
  'great',
  'new',
  'old',
  'high',
  'low',
]);

export const PRIMARY_PRODUCT_TYPES = new Set([
  'sofa',
  'chair',
  'table',
  'bed',
  'cabinet',
  'wardrobe',
  'almirah',
  'dining',
  'office',
  'bedroom',
  'living',
]);

export const SYNONYM_GROUPS = {
  seating: ['sofa', 'chair', 'couch', 'sectional', 'loveseat', 'recliner', 'bench', 'stool'],
  storage: ['cabinet', 'wardrobe', 'almirah', 'cupboard', 'shelf', 'dresser', 'chest'],
  sleeping: ['bed', 'mattress', 'cot', 'crib'],
  surface: ['table', 'desk', 'console', 'counter'],
  material_wood: ['wood', 'wooden', 'timber', 'oak', 'pine', 'teak', 'mahogany'],
  material_metal: ['metal', 'steel', 'iron', 'aluminum', 'brass'],
  material_fabric: ['fabric', 'cloth', 'cotton', 'linen', 'velvet', 'silk'],
};

export function getSynonymGroup(term) {
  for (const [group, terms] of Object.entries(SYNONYM_GROUPS)) {
    if (terms.includes(term.toLowerCase())) {
      return { group, terms };
    }
  }
  return null;
}